incredible squaring -rs
Layr-Labs/eigensdk-rs pull request #84
Opened 2024-08-20 14:05 UTC by supernovahs

This PR contains latest code that is being pulled by incredible squaring rs repo . 

This includes 
- Small nits
- Bug fixes that we come across  while building IS
- other features

goal is to get it reviewed continuously till  IS is complete . Then merge this as well

2024-08-28 15:09 UTC, dralves requested changes

2024-08-28 15:09 UTC, dralves commented on crates/chainio/clients/elcontracts/src/reader.rs
> +            get_provider(&"http://localhost:8545"),
why not use a constant

2024-08-28 15:09 UTC, dralves commented on crates/chainio/clients/elcontracts/src/writer.rs
> +        println!("tokens result {:?}",tokens_result);
hum, println in the middle of prod code?

2024-08-28 15:09 UTC, dralves commented on crates/services/avsregistry/src/chaincaller.rs
> +        println!("operator stakes in quorums {:?}",operators_stakes_in_quorums);
should this be a debug statement

2024-08-28 15:09 UTC, dralves commented on crates/services/avsregistry/src/chaincaller.rs
> +                    println!("quorum_num {:?}",quorum_num);
same, here and elsewhere

2024-08-28 15:09 UTC, dralves commented on examples/info-operator-service/src/main.rs
> +// use alloy_primitives::address;
this seems messy

2024-08-28 15:11 UTC, supernovahs commented on crates/services/avsregistry/src/chaincaller.rs
> +        println!("operator stakes in quorums {:?}",operators_stakes_in_quorums);
my bad , forgot to remove these prints.

2024-08-28 20:15 UTC, supernovahs commented on examples/info-operator-service/src/main.rs
> +// use alloy_primitives::address;
done

2024-08-28 20:15 UTC, supernovahs commented
pending merge from main

2024-08-29 14:42 UTC, dralves approved these changes

2024-08-29 15:00 UTC, merged