BLS-aggregation integration tests
Layr-Labs/eigensdk-rs pull request #91
Opened 2024-08-27 18:37 UTC by TomasArrachea

Implemented integration tests for `bls_aggregation` crate.
Added 5 tests:

- 2 quorums 1 operator (ignored)
- 2 quorums 2 operators shared (ignored)
- 1 quorum 1 operator
- 1 quorum 2 operators 
- 2 quorums 2 operators separated

Two cases are ignored as they are failing due to this bug: [bls aggregation service doesn't support >1 quorum](https://github.com/Layr-Labs/eigensdk-go/issues/261)

2024-08-28 14:57 UTC, supernovahs requested changes

2024-08-28 14:57 UTC, supernovahs commented on crates/crypto/bls/src/lib.rs
> +/// Convert [`G2Affine`] to [`G2Point`]
```suggestion
/// Convert [`G2Affine`] to [`G2PointRegistry `]
```

2024-08-28 14:57 UTC, supernovahs commented on crates/crypto/bls/src/lib.rs
> +/// Convert [`G1Point`] to [`G1Affine`]
comment

2024-08-28 14:57 UTC, supernovahs commented on crates/crypto/bls/src/lib.rs
> +/// Convert [`G1Affine`] to  Alloy [`G1Point`]
comment update needed

2024-08-28 14:57 UTC, supernovahs commented on crates/crypto/bls/src/lib.rs
> +/// Convert [`G1Affine`] to  Alloy [`G1Point`]
```suggestion
/// Convert [`G1Affine`] to  Alloy [`G1PointChecker `]
```

2024-08-28 15:01 UTC, supernovahs commented
regarding the issue of adding separate conversion for different bindings. 
Maybe we can reuse the original conversion functions, instead of adding separate for each bindings by unwrapping the X and Y values and wrapping in appropriate binding variant in the crate we need. (we can also use the above conversion functions in the lib.rs of those crates and use those their as helper also)

If you think above is a better way . Otherwise all good. some small nits

2024-08-28 21:16 UTC, TomasArrachea commented
> regarding the issue of adding separate conversion for different bindings. Maybe we can reuse the original conversion functions, instead of adding separate for each bindings by unwrapping the X and Y values and wrapping in appropriate binding variant in the crate we need. (we can also use the above conversion functions in the lib.rs of those crates and use those their as helper also)
> 
> If you think above is a better way . Otherwise all good. some small nits

@supernovahs I think it's better to merge the PR as is, and then make the refactor in a separate PR if needed.

2024-08-30 14:29 UTC, supernovahs commented
needs a main merge

2024-08-30 17:11 UTC, merged